services:
  python311:
    restart: always
    build: .
    container_name: 'langchain_academy'
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_ENDPOINT=${LANGCHAIN_ENDPOINT}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    working_dir: /langchain-academy
    tty: true
    ports:
      - '8888:8888'
    volumes:
      - ./:/langchain-academy
